#!/usr/bin/env bash
# Vendor the canonical tables and crate version into this package before
# packing. The repository keeps no duplicates: `tables/` and `Cargo.toml`
# at the cgreet root stay canonical; `src/generated/` is regenerated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

mkdir -p "$HERE/src/generated"

VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*"\(.*\)"/\1/')"

python3 - "$HERE" "$ROOT" "$VERSION" <<'EOF'
import json
import sys

here, root, version = sys.argv[1], sys.argv[2], sys.argv[3]
with open(f"{root}/tables/de.json", encoding="utf-8") as handle:
    de = json.load(handle)
out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    "export interface DeTable {\n"
    "  locale: string;\n"
    "  source_norms: string;\n"
    "  honorifics: Record<string, string>;\n"
    "  titles: Record<string, string>;\n"
    "  sole_titles: string[];\n"
    "  filler: string[];\n"
    "  comma_regions: string[];\n"
    "  generic: string;\n"
    "}\n"
    f"export const PACKAGE_VERSION: string = {json.dumps(version)};\n"
    f"export const DE_TABLE: DeTable = {json.dumps(de, ensure_ascii=False)};\n"
)
with open(f"{here}/src/generated/tables.ts", "w", encoding="utf-8") as handle:
    handle.write(out)
print(f"synced tables/de.json, version {version}")
EOF

python3 "$ROOT/scripts/sync-python.py"
